### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Pakillo** [VeruGHub/easyclimate#7]
- [X] Create package structure
- [x] Revise functions one by one (code & documentation)
- [x] Add tests & coverage
- [x] Add continuous integration (GitHub Actions)
- [x] Add vignettes/tutorials
- [x] Create website with pkgdown
- [x] Write note for publication 
- [ ] Upload to CRAN
- [ ] Submit to rOpenSci?

**Comment by Pakillo** [comment]
For CRAN submission:

https://github.com/ThinkR-open/prepare-for-cran

https://github.com/tidyverse/multidplyr/issues/109

**Comment by Pakillo** [comment]
https://books.ropensci.org/http-testing/index.html

https://github.com/ropensci/vcr
